In [51]:
# Import de bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
# Leitura do dataset
df = pd.read_csv('dataset/clientes.csv', sep=',')
df.head()

,Ordem,ID,x1 - comida de excelente qualidade,x2 - Interior atraente,x3 - porcoes generosas,x4 - comida com gosto excelente,x5 - bom valor para o dinheiro,x6 - funcionarios simpaticos,x7 - aparencia limpa e organizada,x8 - ambiente divertido,...,x13 - satisfacao,x14 - voltar no futuro,x15 - recomendacao,x16 - frequencia,x17 - tempo como cliente,x18 - genero,x19 - idade,x20 - renda,x21 - retornou,x22 - restaurantes
0,1,1,5,1,5,5,5,3,1,1,...,5,5,5,3,3,0,3,5,1,Giino
1,2,2,5,1,5,5,5,3,1,1,...,5,5,5,3,3,0,3,5,1,Giino
2,3,3,5,1,5,5,5,3,1,1,...,5,5,5,3,3,0,3,5,1,Giino
3,4,4,5,1,5,5,5,3,1,1,...,5,5,5,3,3,0,3,5,1,Giino
4,5,5,5,1,5,5,5,3,1,1,...,5,5,5,3,3,0,3,5,1,Giino

## Tratamento de dados

#### Funções para tratamento dos dados

In [53]:
# Funções de tratamento de dados
'''
['Ordem ', 'ID', 'x1 - comida de excelente qualidade',
       'x2 - Interior atraente', 'x3 - porcoes generosas',
       'x4 - comida com gosto excelente', 'x5 - bom valor para o dinheiro',
       'x6 - funcionarios simpaticos', 'x7 - aparencia limpa e organizada',
       'x8 - ambiente divertido', 'x9 - variedades de produtos',
       'x10 - precos razoaveis', 'x11 - funcionarios gentis',
       'x12 - funcionarios competentes', 'x13 - satisfacao',
       'x14 - voltar no futuro', 'x15 - recomendacao', 'x16 - frequencia',
       'x17 - tempo como cliente', 'x18 - genero', 'x19 - idade',
       'x20 - renda', 'x21 - retornou', 'x22 - restaurantes'],
'''

# frequencia
def tratamento_frequencia(valor):
    if valor == 1:
        df['x16 - frequencia'].replace(valor, 'Ocasional', inplace=True)
    elif valor == 2:
        df['x16 - frequencia'].replace(valor, 'Com frequência', inplace=True)
    elif valor == 3:
        df['x16 - frequencia'].replace(valor, 'Muita frequência', inplace=True)
    else:
        df['x16 - frequencia'].replace(valor, 'Não informado', inplace=True)


# genero
def tratamento_genero(valor):
    if valor == 0:
        df['x18 - genero'].replace(valor, 'Masculino', inplace=True)
    elif valor == 1:
        df['x18 - genero'].replace(valor, 'Feminino', inplace=True)
    else:
        df['x18 - genero'].replace(valor, 'Outro', inplace=True)


# idade
def tratamento_idade(valor):
    if valor == 1:
        df['x19 - idade'].replace(valor, '18-25 anos', inplace=True)
    elif valor == 2:
        df['x19 - idade'].replace(valor, '26-34 anos', inplace=True)
    elif valor == 3:
        df['x19 - idade'].replace(valor, '35-49 anos', inplace=True)
    elif valor == 4:
        df['x19 - idade'].replace(valor, '50-59 anos', inplace=True)
    elif valor == 5:
        df['x19 - idade'].replace(valor, '60 anos ou mais', inplace=True)
    else:
        df['x19 - idade'].replace(valor, 'Outro', inplace=True)


# renda
def tratamento_renda(valor):
    if valor == 1:
        df['x20 - renda'].replace(valor, '$20.000 - $35.000 anuais', inplace=True)
    elif valor == 2:
        df['x20 - renda'].replace(valor, '$35.001 - $50.000 anuais', inplace=True)
    elif valor == 3:
        df['x20 - renda'].replace(valor, '$50.001 - $75.000 anuais', inplace=True)
    elif valor == 4:
        df['x20 - renda'].replace(valor, '$75.001 - $100.000 anuais', inplace=True)
    elif valor == 5:
        df['x20 - renda'].replace(valor, '$100.000 anuais', inplace=True)
    else:
        df['x20 - renda'].replace(valor, 'Outro', inplace=True)

# Retornara ao restaurante
def tratamento_retornaria(valor):
    if valor == 0:
        df['x21 - retornou'].replace(valor, 'Não retornaria', inplace=True)
    elif valor == 1:
        df['x21 - retornou'].replace(valor, 'Retornaria', inplace=True)
    else:
        df['x21 - retornou'].replace(valor, 'Outro', inplace=True)

#### Realização do tratamento

In [54]:
# Realizar o tratamento dos dados de cada linhas em relação as respectivas colunas do dataset
for coluna in df.columns:
    match coluna:
        case 'x16 - frequencia':
            print('Tratando coluna: ', coluna)
            for i in df[coluna]:
                tratamento_frequencia(i)
        case 'x18 - genero':
            print('Tratando coluna: ', coluna)
            for i in df[coluna]:
                tratamento_genero(i)
        case 'x19 - idade':
            print('Tratando coluna: ', coluna)
            for i in df[coluna]:
                tratamento_idade(i)
        case 'x20 - renda':
            print('Tratando coluna: ', coluna)
            for i in df[coluna]:
                tratamento_renda(i)
        case 'x21 - retornou':
            print('Tratando coluna: ', coluna)
            for i in df[coluna]:
                tratamento_retornaria(i)
        case _:
            pass

# Verificar o dataset tratado
df.head()

Tratando coluna:  x16 - frequencia
Tratando coluna:  x18 - genero
Tratando coluna:  x19 - idade
Tratando coluna:  x20 - renda
Tratando coluna:  x21 - retornou

,Ordem,ID,x1 - comida de excelente qualidade,x2 - Interior atraente,x3 - porcoes generosas,x4 - comida com gosto excelente,x5 - bom valor para o dinheiro,x6 - funcionarios simpaticos,x7 - aparencia limpa e organizada,x8 - ambiente divertido,...,x13 - satisfacao,x14 - voltar no futuro,x15 - recomendacao,x16 - frequencia,x17 - tempo como cliente,x18 - genero,x19 - idade,x20 - renda,x21 - retornou,x22 - restaurantes
0,1,1,5,1,5,5,5,3,1,1,...,5,5,5,Muita frequência,3,Masculino,35-49 anos,$100.000 anuais,Retornaria,Giino
1,2,2,5,1,5,5,5,3,1,1,...,5,5,5,Muita frequência,3,Masculino,35-49 anos,$100.000 anuais,Retornaria,Giino
2,3,3,5,1,5,5,5,3,1,1,...,5,5,5,Muita frequência,3,Masculino,35-49 anos,$100.000 anuais,Retornaria,Giino
3,4,4,5,1,5,5,5,3,1,1,...,5,5,5,Muita frequência,3,Masculino,35-49 anos,$100.000 anuais,Retornaria,Giino
4,5,5,5,1,5,5,5,3,1,1,...,5,5,5,Muita frequência,3,Masculino,35-49 anos,$100.000 anuais,Retornaria,Giino

## Análise dos dados

Realização de análises descritivas das variáveis de classificação abaixo para entender o perfil demográfico dos clientes de cada restaurante:
- Idade
- Gênero
- Renda

Isso pode ser feito por meio de gráficos e tabelas que mostram a distribuição dos dados nessas variáveis.